export const session02Data = {
  roles: [
    { number: "01", title: "TEAM CAPTAIN", korean: "팀장 · Flow Caller", responsibility: "지시 수신 · 단계 전환 · READY 보고 · 임의 진행 방지" },
    { number: "02", title: "SAFETY & SANITATION LEAD", korean: "안전 · 장비 살균 담당", responsibility: "뜨거운 작업 안전 · sanitizer(살균세척액) · cold-side 장비 위생" },
    { number: "03", title: "INGREDIENT & HOP PREP LEAD", korean: "원료·홉 준비 담당", responsibility: "추출물 확인 · 홉 계량 · T-30/T-10/T-0 컵 라벨" },
    { number: "04", title: "KETTLE & HEAT LEAD", korean: "가열·보일 담당", responsibility: "열원 · 추출물 용해 · boil-over 감시" },
    { number: "05", title: "TIMER & HOP CALLER", korean: "타이머·홉 콜 담당", responsibility: "Master Clock · 1분 전 알림 · 투입 시점 확인" },
    { number: "06", title: "MEASUREMENT & RECORD LEAD", korean: "측정·기록 담당", responsibility: "온도 · 실제 홉 시각 · OG(초기비중) · Brew Record" },
    { number: "07", title: "COOLING · TRANSFER · YEAST LEAD", korean: "냉각·이송·효모 담당", responsibility: "냉각 · 이송 · 피칭 온도 · 효모 · 최종 label" },
  ],
  teams: {
    pink: {
      color: "PINK",
      style: "HEFEWEIZEN",
      focus: "FERMENTATION-LED",
      sensory: "BANANA · CLOVE · SOFT",
      members: ["조두연", "송승의", "김경희B", "황재순", "신기식", "이장혁", "조현수"],
    },
    green: {
      color: "GREEN",
      style: "AMERICAN PALE ALE",
      focus: "HOP-LED",
      sensory: "GRAPEFRUIT · CITRUS · PINE",
      members: ["한안나", "김현미", "박은형", "김미연", "김경희A", "염혜정", "배진수"],
    },
    yellow: {
      color: "YELLOW",
      style: "ENGLISH BROWN ALE",
      focus: "MALT-LED",
      sensory: "CARAMEL · TOFFEE · CHOCOLATE",
      members: ["권진영", "권영옥", "이종연", "장세미", "권재폄", "허주행", "홍석민"],
    },
  },
  recipes: {
    pink: {
      team: "TEAM PINK",
      style: "HEFEWEIZEN",
      korean: "헤페바이젠",
      focus: "FERMENTATION-LED · BANANA · CLOVE · SOFT",
      extract: ["BRIESS BAVARIAN WHEAT DME · 2.5kg"],
      hops: ["T-30 · HALLERTAUER TRADITION · 14g", "T-10 · HALLERTAUER TRADITION · 14g"],
      yeast: "SafAle WB-06 · 2 PACKS",
      startWater: "20L",
      volume: "TARGET 19.5–20L · NO TOP-UP",
      expected: { og: "1.045–1.050", fg: "1.010–1.012", abv: "4.4–5.0%", ibu: "8.2–14.4 · MID ≈11.3", pitchTemp: "≤24°C", fermentTemp: "≈20°C" },
      targets: ["OG 1.045–1.050", "FG 1.010–1.012", "ABV 4.4–5.0%", "IBU MIDPOINT ≈ 11.3", "COOL ≤24°C", "FERMENT ≈20°C"],
    },
    green: {
      team: "TEAM GREEN",
      style: "AMERICAN PALE ALE",
      korean: "아메리칸 페일 에일",
      focus: "HOP-LED · GRAPEFRUIT · CITRUS · PINE",
      extract: ["BRIESS GOLDEN LIGHT DME · 2.0kg", "SPARKLING AMBER DME · 0.5kg"],
      hops: ["T-30 · CASCADE · 28g", "T-10 · CASCADE · 28g", "T-0 · CASCADE · 28g · 5–10 MIN HOPSTAND"],
      yeast: "SafAle US-05 · 2 PACKS",
      startWater: "20L",
      volume: "TARGET 19.5–20L · NO TOP-UP",
      expected: { og: "1.045–1.050", fg: "1.010–1.012", abv: "4.7–5.1%", ibu: "21.8–43.5 · MID ≈32.6", pitchTemp: "≤24°C", fermentTemp: "≈20°C" },
      targets: ["OG 1.045–1.050", "FG 1.010–1.012", "ABV 4.7–5.1%", "IBU MIDPOINT ≈ 32.6", "COOL ≤24°C", "FERMENT ≈20°C"],
    },
    yellow: {
      team: "TEAM YELLOW",
      style: "ENGLISH BROWN ALE",
      korean: "잉글리시 브라운 에일",
      focus: "MALT-LED · CARAMEL · TOFFEE · CHOCOLATE",
      extract: ["SPARKLING AMBER DME · 1.25kg", "TRADITIONAL DARK LME · 1.5kg"],
      hops: ["T-30 · UK EAST KENT GOLDING · 28g"],
      yeast: "SafAle S-04 · 2 PACKS",
      startWater: "20L",
      volume: "TARGET 19.5–20L · NO TOP-UP",
      expected: { og: "1.044–1.048", fg: "1.012–1.014", abv: "4.3–4.8%", ibu: "11.3–20.1 · MID ≈15.7", pitchTemp: "≤24°C", fermentTemp: "≈20°C" },
      targets: ["OG 1.044–1.048", "FG 1.012–1.014", "ABV 4.3–4.8%", "IBU MIDPOINT ≈ 15.7", "COOL ≤24°C", "FERMENT ≈20°C"],
    },
  },
  liveStates: [
    { code: "A", label: "EXTRACT · 추출물", now: "DISSOLVE EXTRACT · 추출물 녹이기", detail: "70°C · 불을 끄고 · 덩어리 없이 완전히", next: "HEAT TO BOIL · 끓이기", clock: "DISSOLVE", statuses: ["GO", "GO", "GO"] },
    { code: "B", label: "HEAT · 가열", now: "HEAT TO ROLLING BOIL · 끓이기", detail: "가열 시작 · 롤링 보일까지", next: "READY GATE · 세 팀 준비 확인", clock: "UNTIL BOIL", statuses: ["GO", "GO", "GO"] },
    { code: "C", label: "READY GATE · 준비 확인", now: "TEAM CAPTAINS REPORT · 팀장 보고", detail: "세 팀 모두 롤링 보일 준비됐나요?", next: "3 · 2 · 1 · 보일 시작", clock: "ALL READY", statuses: ["READY", "READY", "READY"] },
    { code: "D", label: "MASTER BOIL · 보일", now: "30:00 · 보일 시작", detail: "T-30 홉 지금 투입", next: "HOP ALERT · 10분 전", statuses: ["GO", "GO", "GO"], timer: true },
    { code: "E", label: "HOPS + CHILLER · 홉과 칠러", now: "10:00 LEFT · T-10", detail: "세 팀 칠러 투입 · PINK 14g · GREEN 28g", next: "FLAMEOUT · 불 끄기", statuses: ["GO", "GO", "GO"], alert: "t10", timer: true },
    { code: "F", label: "FLAMEOUT · 불 끄기", now: "00:00 · HEAT OFF · 불 끄기", detail: "PINK/YELLOW 냉각 시작 · GREEN 28g + 5–10분 홉스탠드", next: "COOL THE WORT · 맥즙 냉각", clock: "00:00", statuses: ["COOL", "HOPSTAND", "COOL"], alert: "zero" },
    { code: "G", label: "COOLING · 냉각", now: "COOL THE WORT · 맥즙 냉각 ≤24°C", detail: "구리 칠러 + 케틀 바깥 얼음물", next: "TRANSFER · 이송", clock: "COOL", statuses: ["GO", "GO", "GO"] },
    { code: "H", label: "TRANSFER · 이송", now: "살균한 발효조로 이송", detail: "추가 급수 없이 · 목표 19.5–20L", next: "MEASURE OG + TEMP · 측정", clock: "MOVE", statuses: ["GO", "GO", "GO"] },
    { code: "I", label: "MEASURE · 측정", now: "OG(초기비중) → 온도", detail: "효모 투입 조건 · ≤24°C", next: "PITCH YEAST · 효모 투입", clock: "CHECK", statuses: ["READY", "READY", "READY"] },
    { code: "J", label: "YEAST · 효모", now: "PITCH · 효모 2팩 투입", detail: "WB-06 · US-05 · S-04", next: "CLOSE + LABEL · 밀봉과 라벨", clock: "PITCH", statuses: ["GO", "GO", "GO"] },
    { code: "K", label: "CLOSE · 밀봉", now: "뚜껑 → 에어락 → 라벨", detail: "팀 · 스타일 · 양조일 · OG", next: "BATCH STARTED · 발효 시작", clock: "CLOSE", statuses: ["DONE", "DONE", "DONE"] },
    { code: "L", label: "DONE · 완료", now: "BATCH 01 · 발효 시작", detail: "이제 여러분이 없는 동안 효모가 계속 일합니다.", next: "BEER IN TRANSITION · 변화 관찰", clock: "START", statuses: ["DONE", "DONE", "DONE"] },
  ],
};
