export const session03Data = {
  teams: {
    pink: {
      color: "PINK",
      style: "HEFEWEIZEN",
      korean: "헤페바이젠",
      volume: 19,
      og: 1.051,
      expectedFg: "1.007–1.011",
      expectedFgRange: [1.007, 1.011],
      yeast: "SafAle WB-06",
      targetCo2: 2.55,
      bottleEstimate: "34–36",
      focus: "BANANA · CLOVE · SOFT",
    },
    green: {
      color: "GREEN",
      style: "AMERICAN PALE ALE",
      korean: "아메리칸 페일 에일",
      volume: 14.5,
      og: 1.068,
      expectedFg: "1.012–1.016",
      expectedFgRange: [1.012, 1.016],
      yeast: "SafAle US-05",
      targetCo2: 2.35,
      bottleEstimate: "26–28",
      focus: "GRAPEFRUIT · CITRUS · PINE",
    },
    yellow: {
      color: "YELLOW",
      style: "ENGLISH BROWN ALE",
      korean: "잉글리시 브라운 에일",
      volume: 19,
      og: 1.050,
      expectedFg: "1.010–1.014",
      expectedFgRange: [1.010, 1.014],
      yeast: "SafAle S-04",
      targetCo2: 2.10,
      bottleEstimate: "34–36",
      focus: "CARAMEL · TOFFEE · CHOCOLATE",
    },
  },
  roles: [
    { number: "01", title: "TEAM CAPTAIN", korean: "팀장 · Flow Caller", responsibility: "강사 지시 수신 · 단계 전환 · 팀 READY 보고" },
    { number: "02", title: "FG & RECORD LEAD", korean: "FG 측정 · 기록 담당", responsibility: "샘플 채취 · 비중 측정 · 실제 FG와 병 수 기록" },
    { number: "03", title: "SANITATION LEAD", korean: "살균 담당", responsibility: "PET병 · 뚜껑 · 버킷 · 사이펀 · 튜브 살균" },
    { number: "04", title: "PRIMING LEAD", korean: "프라이밍 담당", responsibility: "팀별 병당 설탕량 계량 · 교차 확인" },
    { number: "05", title: "SIPHON & TRANSFER", korean: "사이펀 · 이송 담당", responsibility: "침전물 회피 · 조용한 이송 · 튜브 위치 유지" },
    { number: "06", title: "FILL & CAP", korean: "충전 · 밀봉 담당", responsibility: "물꼭지 직접 충전 · 헤드스페이스 · 즉시 밀봉" },
    { number: "07", title: "LABEL · STORE · CLEAN", korean: "라벨 · 보관 · 정리 담당", responsibility: "라벨 확인 · 컨테이너 보관 · 스테이션 정리" },
  ],
  liveStates: [
    { code: "A", label: "SANITIZE · 살균", now: "EVERY CONTACT SURFACE", detail: "병입 버킷 · 물꼭지 · 사이펀 · 튜브 · 실린더 · PET병 · 뚜껑", next: "OPEN · 뚜껑 열고 관찰", statuses: ["SANITIZE", "SANITIZE", "SANITIZE"] },
    { code: "B", label: "OBSERVE · 관찰", now: "OPEN · LOOK · SMELL", detail: "오프너로 뚜껑을 열면, 건드리기 전에 표면과 향을 관찰합니다.", next: "SIPHON · 병입 버킷으로 이송", statuses: ["OBSERVE", "OBSERVE", "OBSERVE"] },
    { code: "C", label: "SIPHON · 사이펀", now: "TRANSFER FIRST.", detail: "침전물을 피해 병입 버킷으로 조용히 전량 이송합니다.", next: "SAMPLE · 물꼭지에서 채취", statuses: ["TRANSFER", "TRANSFER", "TRANSFER"] },
    { code: "D", label: "SAMPLE · 샘플", now: "SAMPLE BEFORE SUGAR.", detail: "설탕을 넣기 전, 살균한 물꼭지에서 실린더로 필요한 양만 받습니다.", next: "MEASURE FG · 최종비중 측정", statuses: ["SAMPLE", "SAMPLE", "SAMPLE"] },
    { code: "E", label: "MEASURE · 측정", now: "FLOAT · EYE LEVEL · RECORD", detail: "거품을 가라앉히고 FG를 읽어 Brew Record에 기록합니다.", next: "CONFIRM · 설탕량 결정", statuses: ["FG", "FG", "FG"] },
    { code: "F", label: "CONFIRM · 결정", now: "FG FIRST. SUGAR SECOND.", detail: "실측 FG를 확인하고 각 팀의 500mL 병당 설탕량을 결정합니다.", next: "PRIME · 병별 설탕 계량", statuses: ["CHECK", "CHECK", "CHECK"] },
    { code: "G", label: "PRIME · 프라이밍", now: "MEASURE EACH BOTTLE", detail: "현장에서 결정한 팀별 양 · __ g / 500mL", next: "FILL · PET병 충전", statuses: ["__ g", "__ g", "__ g"] },
    { code: "H", label: "FILL · 충전", now: "DIRECT FILL · 직접 충전", detail: "PET병 입구를 물꼭지 가까이 · 병 벽면을 따라 천천히", next: "CAP · 즉시 밀봉", statuses: ["FILL", "FILL", "FILL"] },
    { code: "I", label: "CAP · 밀봉", now: "FILL → CAP → NEXT", detail: "한 병씩 채우고 바로 내압 뚜껑을 잠급니다.", next: "LABEL · STORE · 라벨과 보관", statuses: ["CAP", "CAP", "CAP"] },
    { code: "J", label: "LABEL · STORE", now: "BATCH · DATE · FG", detail: "팀별 컨테이너에 넣고 학교 발효 공간에 보관합니다.", next: "CLEAN · 정리", statuses: ["STORE", "STORE", "STORE"] },
    { code: "K", label: "CLEAN · 완료", now: "EMPTY · RINSE · RETURN", detail: "장비를 세척하고 수량과 기록을 최종 확인합니다.", next: "ALE, TWO WAYS · 비교 시음", statuses: ["DONE", "DONE", "DONE"] },
  ],
  tasting: {
    tribute: {
      code: "A",
      name: "ST AUSTELL TRIBUTE PALE ALE",
      abv: "4.2%",
      image: "./assets/st-austell-tribute.png",
      imageAlt: "St Austell Tribute Pale Ale 캔과 병, 잔, 캐스크 핸들",
      cues: "MALT BALANCE · ORANGE · GRAPEFRUIT",
      process: "BRITISH ALE · CASK-BEER ROOTS",
      processKo: "영국식 에일 · 캐스크 맥주의 전통",
    },
    saison: {
      code: "B",
      name: "SAISON DUPONT",
      abv: "6.5%",
      image: "./assets/saison-dupont-product.jpg",
      imageAlt: "Saison Dupont 750mL 병과 맥주잔",
      cues: "DRY · LIVELY · CLOVE · WHITE FRUIT",
      process: "BELGIAN SAISON · BOTTLE REFERMENTATION",
      processKo: "벨기에 세종 · 병 속에서 다시 발효",
    },
  },
};
