export const session03Data = {
  teams: {
    pink: {
      color: "PINK",
      style: "HEFEWEIZEN",
      korean: "헤페바이젠",
      volume: 19,
      og: 1.051,
      expectedFg: "1.007–1.011",
      yeast: "SafAle WB-06",
      prime: 3.4,
      targetCo2: 2.55,
      bottleEstimate: "34–36",
      focus: "BANANA · CLOVE · SOFT",
    },
    green: {
      color: "GREEN",
      style: "AMERICAN PALE ALE",
      korean: "아메리칸 페일 에일",
      volume: 14.5,
      og: 1.068,
      expectedFg: "1.012–1.016",
      yeast: "SafAle US-05",
      prime: 3.0,
      targetCo2: 2.35,
      bottleEstimate: "26–28",
      focus: "GRAPEFRUIT · CITRUS · PINE",
    },
    yellow: {
      color: "YELLOW",
      style: "ENGLISH BROWN ALE",
      korean: "잉글리시 브라운 에일",
      volume: 19,
      og: 1.050,
      expectedFg: "1.010–1.014",
      yeast: "SafAle S-04",
      prime: 2.5,
      targetCo2: 2.10,
      bottleEstimate: "34–36",
      focus: "CARAMEL · TOFFEE · CHOCOLATE",
    },
  },
  roles: [
    { number: "01", title: "TEAM CAPTAIN", korean: "팀장 · Flow Caller", responsibility: "강사 지시 수신 · 단계 전환 · 팀 READY 보고" },
    { number: "02", title: "FG & RECORD LEAD", korean: "FG 측정 · 기록 담당", responsibility: "샘플 채취 · 비중 측정 · 실제 FG와 병 수 기록" },
    { number: "03", title: "SANITATION LEAD", korean: "살균 담당", responsibility: "PET병 · 뚜껑 · 버킷 · 사이펀 · 튜브 살균" },
    { number: "04", title: "PRIMING LEAD", korean: "프라이밍 담당", responsibility: "팀별 병당 설탕량 계량 · 교차 확인" },
    { number: "05", title: "SIPHON & TRANSFER", korean: "사이펀 · 이송 담당", responsibility: "침전물 회피 · 조용한 이송 · 튜브 위치 유지" },
    { number: "06", title: "FILL & CAP", korean: "충전 · 밀봉 담당", responsibility: "바닥부터 충전 · 헤드스페이스 · 즉시 밀봉" },
    { number: "07", title: "LABEL · STORE · CLEAN", korean: "라벨 · 보관 · 정리 담당", responsibility: "라벨 확인 · 컨테이너 보관 · 스테이션 정리" },
  ],
  liveStates: [
    { code: "A", label: "OBSERVE · 관찰", now: "LOOK · SMELL · LISTEN", detail: "뚜껑을 열기 전, 변화의 증거부터 찾습니다.", next: "SAMPLE · 샘플 채취", statuses: ["OBSERVE", "OBSERVE", "OBSERVE"] },
    { code: "B", label: "SAMPLE · 샘플", now: "SANITIZED SAMPLE ONLY", detail: "살균한 도구로 필요한 양만 채취합니다.", next: "MEASURE FG · 최종비중 측정", statuses: ["SAMPLE", "SAMPLE", "SAMPLE"] },
    { code: "C", label: "MEASURE · 측정", now: "FLOAT · EYE LEVEL · RECORD", detail: "FG를 읽고 Brew Record에 기록합니다.", next: "INSTRUCTOR GATE · 강사 판정", statuses: ["FG", "FG", "FG"] },
    { code: "D", label: "GATE · 판정", now: "FG FIRST. SUGAR SECOND.", detail: "각 팀은 강사의 GO 또는 HOLD를 기다립니다.", next: "SANITIZE · 병입 장비 살균", statuses: ["WAIT", "WAIT", "WAIT"] },
    { code: "E", label: "SANITIZE · 살균", now: "EVERY CONTACT SURFACE", detail: "PET병 · 뚜껑 · 버킷 · 수도꼭지 · 사이펀 · 튜브", next: "PRIME · 병별 설탕 계량", statuses: ["CLEAN", "CLEAN", "CLEAN"] },
    { code: "F", label: "PRIME · 프라이밍", now: "MEASURE EACH BOTTLE", detail: "Pink 3.4g · Green 3.0g · Yellow 2.5g / 500mL", next: "SIPHON · 병입 버킷으로 이송", statuses: ["3.4g", "3.0g", "2.5g"] },
    { code: "G", label: "SIPHON · 사이펀", now: "TRANSFER QUIETLY", detail: "침전물을 피해 위쪽부터 · 튜브 끝은 버킷 바닥 가까이", next: "FILL · PET병 충전", statuses: ["MOVE", "MOVE", "MOVE"] },
    { code: "H", label: "FILL · 충전", now: "FILL FROM THE BOTTOM", detail: "짧은 살균 튜브로 바닥부터 · 일정한 헤드스페이스", next: "CAP · 즉시 밀봉", statuses: ["FILL", "FILL", "FILL"] },
    { code: "I", label: "CAP · 밀봉", now: "FILL → CAP → NEXT", detail: "한 병씩 채우고 바로 내압 뚜껑을 잠급니다.", next: "LABEL · STORE · 라벨과 보관", statuses: ["CAP", "CAP", "CAP"] },
    { code: "J", label: "LABEL · STORE", now: "BATCH · DATE · FG", detail: "팀별 컨테이너에 넣고 학교 발효 공간에 보관합니다.", next: "CLEAN · 정리", statuses: ["STORE", "STORE", "STORE"] },
    { code: "K", label: "CLEAN · 완료", now: "EMPTY · RINSE · RETURN", detail: "장비를 세척하고 수량과 기록을 최종 확인합니다.", next: "ALE, TWO WAYS · 비교 시음", statuses: ["DONE", "DONE", "DONE"] },
  ],
  tasting: {
    tribute: {
      code: "A",
      name: "ST AUSTELL TRIBUTE PALE ALE",
      abv: "4.2%",
      cues: "MALT BALANCE · ORANGE · GRAPEFRUIT",
      process: "BRITISH ALE · CASK-BEER ROOTS",
    },
    saison: {
      code: "B",
      name: "SAISON DUPONT",
      abv: "6.5%",
      cues: "DRY · LIVELY · CLOVE · WHITE FRUIT",
      process: "BELGIAN SAISON · BOTTLE REFERMENTATION",
    },
  },
};
